// 数据文件 - 包含所有组、任务、成就的信息
const DATA = {
    // 任务组数据
    groups: [
        { id: 'y', name: '默认组', description: '系统默认的任务组' },
        { id: 'A', name: '学习组', description: '专注于学习和知识获取的任务组' },
        { id: 'B', name: '运动组', description: '体育锻炼和健康管理的任务组' },
        { id: 'C', name: '生活组', description: '日常生活和家务管理的任务组' },
        { id: 'D', name: '娱乐组', description: '休闲娱乐和兴趣爱好的任务组' },
        { id: 'E', name: '工作组', description: '工作和职业发展的任务组' }
    ],

    // 日常任务数据
    daily: [
        { id: '00', name: '洗碗', description: '清洗餐具和厨具', coin: 100, diamond: 0 },
        { id: '01', name: '扫地', description: '清扫地面灰尘和杂物', coin: 200, diamond: 0 },
        { id: '02', name: '拖地', description: '用拖把清洁地面', coin: 300, diamond: 0 },
        { id: '03', name: '吃蔬菜干', description: '食用蔬菜干补充营养', coin: 0, diamond: 10 },
        { id: '04', name: '吃水果', description: '食用新鲜水果', coin: 0, diamond: 10 },
        { id: '05', name: '卷腹', description: '进行腹部肌肉训练', coin: 100, diamond: 20 },
        { id: '06', name: '跑圈', description: '进行跑步锻炼', coin: 0, diamond: 20 },
        { id: '07', name: '吊环', description: '进行吊环训练', coin: 100, diamond: 30 },
        { id: '08', name: '看精品书', description: '阅读高质量的书籍', coin: 300, diamond: 30 },
        { id: '09', name: '看垃圾书', description: '阅读轻松娱乐的书籍', coin: 500, diamond: 0 },
        { id: '0a', name: '学本地课程', description: '学习本地存储的课程内容', coin: 300, diamond: 30 },
        { id: '0b', name: '学网盘课程', description: '学习网盘中的课程内容', coin: 300, diamond: 30 },
        { id: '0c', name: '学已购课程', description: '学习已购买的在线课程', coin: 200, diamond: 40 },
        { id: '0d', name: '用护眼仪', description: '使用护眼仪器保护视力', coin: 0, diamond: 10 },
        { id: '0e', name: '剪视频', description: '编辑和剪辑视频内容', coin: 600, diamond: 10 },
        { id: '0f', name: '整理床铺', description: '整理和铺好床铺', coin: 100, diamond: 10 },
        { id: '0g', name: '整理桌面', description: '整理桌面物品和文件', coin: 200, diamond: 10 },
        { id: '0h', name: '整理屋子', description: '整理整个房间的物品', coin: 400, diamond: 20 },
        { id: '0i', name: '整理笔记', description: '整理和归纳学习笔记', coin: 400, diamond: 0 },
        { id: '0j', name: '整理食谱', description: '整理和收集菜谱', coin: 300, diamond: 10 },
        { id: '0k', name: '背单词', description: '背诵英语单词', coin: 500, diamond: 20 },
        { id: '0l', name: '练听写', description: '练习英语听力听写', coin: 400, diamond: 40 },
        { id: '0m', name: '洗澡', description: '进行个人清洁', coin: 300, diamond: 10 },
        { id: '0n', name: '洗头', description: '清洗头发', coin: 300, diamond: 10 },
        { id: '0o', name: '刷牙', description: '清洁牙齿', coin: 50, diamond: 5 },
        { id: '0p', name: '洗脸', description: '清洁面部', coin: 50, diamond: 5 },
        { id: '0q', name: '梳头', description: '梳理头发', coin: 30, diamond: 3 },
        { id: '0r', name: '涂护肤品', description: '使用护肤产品', coin: 100, diamond: 15 },
        { id: '0s', name: '喝水', description: '补充水分', coin: 20, diamond: 2 },
        { id: '0t', name: '吃早餐', description: '享用早餐', coin: 150, diamond: 15 },
        { id: '0u', name: '吃午餐', description: '享用午餐', coin: 150, diamond: 15 },
        { id: '0v', name: '吃晚餐', description: '享用晚餐', coin: 150, diamond: 15 },
        { id: '0w', name: '做运动', description: '进行体育锻炼', coin: 200, diamond: 25 },
        { id: '0x', name: '拉伸', description: '进行身体拉伸运动', coin: 80, diamond: 8 },
        { id: '0y', name: '冥想', description: '进行冥想练习', coin: 120, diamond: 12 },
        { id: '0z', name: '听音乐', description: '欣赏音乐', coin: 60, diamond: 6 },
        { id: '0A', name: '看新闻', description: '阅读新闻资讯', coin: 100, diamond: 10 },
        { id: '0B', name: '看视频', description: '观看视频内容', coin: 80, diamond: 8 },
        { id: '0C', name: '玩游戏', description: '进行游戏娱乐', coin: 50, diamond: 5 },
        { id: '0D', name: '聊天', description: '与他人交流聊天', coin: 40, diamond: 4 },
        { id: '0E', name: '打电话', description: '拨打电话联系他人', coin: 60, diamond: 6 },
        { id: '0F', name: '发消息', description: '发送消息给他人', coin: 30, diamond: 3 },
        { id: '0G', name: '购物', description: '进行购物活动', coin: 200, diamond: 20 },
        { id: '0H', name: '理财', description: '进行理财规划', coin: 300, diamond: 30 },
        { id: '0I', name: '记账', description: '记录日常收支', coin: 100, diamond: 10 },
        { id: '0J', name: '计划', description: '制定计划和目标', coin: 150, diamond: 15 },
        { id: '0K', name: '总结', description: '总结经验和收获', coin: 200, diamond: 20 },
        { id: '0L', name: '反思', description: '进行自我反思', coin: 120, diamond: 12 },
        { id: '0M', name: '学习', description: '进行知识学习', coin: 250, diamond: 25 },
        { id: '0N', name: '复习', description: '复习已学知识', coin: 180, diamond: 18 },
        { id: '0O', name: '练习', description: '进行技能练习', coin: 160, diamond: 16 },
        { id: '0P', name: '创作', description: '进行创意创作', coin: 400, diamond: 40 },
        { id: '0Q', name: '写作', description: '进行文字写作', coin: 350, diamond: 35 },
        { id: '0R', name: '画画', description: '进行绘画创作', coin: 300, diamond: 30 },
        { id: '0S', name: '拍照', description: '拍摄照片', coin: 120, diamond: 12 },
        { id: '0T', name: '录像', description: '录制视频', coin: 200, diamond: 20 },
        { id: '0U', name: '编辑', description: '编辑内容', coin: 250, diamond: 25 },
        { id: '0V', name: '分享', description: '分享内容给他人', coin: 80, diamond: 8 },
        { id: '0W', name: '收藏', description: '收藏喜欢的内容', coin: 40, diamond: 4 },
        { id: '0X', name: '点赞', description: '给内容点赞', coin: 20, diamond: 2 },
        { id: '0Y', name: '评论', description: '发表评论', coin: 60, diamond: 6 },
        { id: '0Z', name: '转发', description: '转发内容', coin: 70, diamond: 7 },
        { id: '10', name: '关注', description: '关注感兴趣的人或内容', coin: 30, diamond: 3 },
        { id: '11', name: '取消关注', description: '取消关注', coin: 20, diamond: 2 },
        { id: '12', name: '举报', description: '举报不当内容', coin: 50, diamond: 5 },
        { id: '13', name: '屏蔽', description: '屏蔽不想看的内容', coin: 40, diamond: 4 },
        { id: '14', name: '删除', description: '删除内容', coin: 30, diamond: 3 },
        { id: '15', name: '恢复', description: '恢复已删除的内容', coin: 60, diamond: 6 },
        { id: '16', name: '备份', description: '备份重要数据', coin: 150, diamond: 15 },
        { id: '17', name: '同步', description: '同步数据到云端', coin: 100, diamond: 10 },
        { id: '18', name: '更新', description: '更新软件或内容', coin: 120, diamond: 12 },
        { id: '19', name: '升级', description: '升级系统或软件', coin: 200, diamond: 20 },
        { id: '1a', name: '降级', description: '降级系统或软件', coin: 50, diamond: 5 },
        { id: '1b', name: '重置', description: '重置设置或数据', coin: 80, diamond: 8 },
        { id: '1c', name: '重启', description: '重启设备或软件', coin: 90, diamond: 9 },
        { id: '1d', name: '关机', description: '关闭设备', coin: 40, diamond: 4 },
        { id: '1e', name: '开机', description: '开启设备', coin: 40, diamond: 4 },
        { id: '1f', name: '充电', description: '给设备充电', coin: 60, diamond: 6 },
        { id: '1g', name: '放电', description: '设备放电', coin: 30, diamond: 3 },
        { id: '1h', name: '清理', description: '清理垃圾文件', coin: 180, diamond: 18 },
        { id: '1i', name: '优化', description: '优化系统性能', coin: 220, diamond: 22 },
        { id: '1j', name: '修复', description: '修复系统问题', coin: 250, diamond: 25 },
        { id: '1k', name: '检查', description: '检查系统状态', coin: 100, diamond: 10 },
        { id: '1l', name: '测试', description: '测试功能', coin: 120, diamond: 12 },
        { id: '1m', name: '调试', description: '调试程序', coin: 200, diamond: 20 },
        { id: '1n', name: '部署', description: '部署应用程序', coin: 300, diamond: 30 },
        { id: '1o', name: '发布', description: '发布内容或产品', coin: 350, diamond: 35 },
        { id: '1p', name: '上线', description: '产品正式上线', coin: 400, diamond: 40 },
        { id: '1q', name: '下线', description: '产品下线', coin: 100, diamond: 10 },
        { id: '1r', name: '维护', description: '系统维护', coin: 280, diamond: 28 },
        { id: '1s', name: '监控', description: '监控系统状态', coin: 150, diamond: 15 },
        { id: '1t', name: '报警', description: '系统报警', coin: 80, diamond: 8 }
    ],

    // 活动任务数据（每周任务）
    weekly: [
        { id: '00', name: '周总结', description: '总结一周的收获和进展', coin: 500, diamond: 50 },
        { id: '01', name: '周计划', description: '制定下周的计划和目标', coin: 400, diamond: 40 },
        { id: '02', name: '周复习', description: '复习一周学习的内容', coin: 600, diamond: 60 },
        { id: '03', name: '周运动', description: '进行一周的运动总结', coin: 300, diamond: 30 },
        { id: '04', name: '周阅读', description: '完成一周的阅读目标', coin: 400, diamond: 40 },
        { id: '05', name: '周创作', description: '完成一周的创作任务', coin: 800, diamond: 80 },
        { id: '06', name: '周学习', description: '学习新的技能或知识', coin: 700, diamond: 70 },
        { id: '07', name: '周整理', description: '整理一周的收获和资料', coin: 300, diamond: 30 },
        { id: '08', name: '周反思', description: '反思一周的表现和改进点', coin: 400, diamond: 40 },
        { id: '09', name: '周分享', description: '分享一周的收获和经验', coin: 200, diamond: 20 },
        { id: '0a', name: '周挑战', description: '完成一周的挑战任务', coin: 1000, diamond: 100 },
        { id: '0b', name: '周突破', description: '在一周内实现某个突破', coin: 1200, diamond: 120 },
        { id: '0c', name: '周创新', description: '尝试新的方法或思路', coin: 600, diamond: 60 },
        { id: '0d', name: '周合作', description: '与他人合作完成项目', coin: 500, diamond: 50 },
        { id: '0e', name: '周展示', description: '展示一周的工作成果', coin: 400, diamond: 40 },
        { id: '0f', name: '周评估', description: '评估一周的工作效果', coin: 300, diamond: 30 },
        { id: '0g', name: '周调整', description: '调整下周的策略和方法', coin: 400, diamond: 40 },
        { id: '0h', name: '周庆祝', description: '庆祝一周的成就', coin: 200, diamond: 20 },
        { id: '0i', name: '周感恩', description: '表达一周的感恩之情', coin: 100, diamond: 10 },
        { id: '0j', name: '周展望', description: '展望下周的期望和目标', coin: 300, diamond: 30 }
    ],

    // 成就数据
    achievements: [
        { id: '00', name: '普通话一乙', description: '获得普通话一乙等级证书', coin: 50000, diamond: 2000 },
        { id: '01', name: '计算机Office二级', description: '获得计算机Office二级证书', coin: 50000, diamond: 2000 },
        { id: '02', name: '计算机Python二级', description: '获得计算机Python二级证书', coin: 100000, diamond: 5000 },
        { id: '03', name: '英语笔译三级', description: '获得英语笔译三级证书', coin: 1000000, diamond: 10000 },
        { id: '04', name: '英语口译三级', description: '获得英语口译三级证书', coin: 800000, diamond: 8000 },
        { id: '05', name: '日语N1', description: '获得日语N1等级证书', coin: 200000, diamond: 3000 },
        { id: '06', name: '日语N2', description: '获得日语N2等级证书', coin: 150000, diamond: 2000 },
        { id: '07', name: '韩语TOPIK6', description: '获得韩语TOPIK6等级证书', coin: 180000, diamond: 2500 },
        { id: '08', name: '韩语TOPIK5', description: '获得韩语TOPIK5等级证书', coin: 120000, diamond: 1500 },
        { id: '09', name: '法语DELF B2', description: '获得法语DELF B2等级证书', coin: 100000, diamond: 1200 },
        { id: '0a', name: '德语TestDaF', description: '获得德语TestDaF等级证书', coin: 120000, diamond: 1500 },
        { id: '0b', name: '西班牙语DELE B2', description: '获得西班牙语DELE B2等级证书', coin: 90000, diamond: 1000 },
        { id: '0c', name: '意大利语CELI B2', description: '获得意大利语CELI B2等级证书', coin: 80000, diamond: 900 },
        { id: '0d', name: '俄语ТРКИ B2', description: '获得俄语ТРКИ B2等级证书', coin: 110000, diamond: 1300 },
        { id: '0e', name: '阿拉伯语HSK', description: '获得阿拉伯语HSK等级证书', coin: 150000, diamond: 2000 },
        { id: '0f', name: '葡萄牙语CAPLE B2', description: '获得葡萄牙语CAPLE B2等级证书', coin: 70000, diamond: 800 },
        { id: '0g', name: '荷兰语NT2', description: '获得荷兰语NT2等级证书', coin: 60000, diamond: 700 },
        { id: '0h', name: '瑞典语SFI', description: '获得瑞典语SFI等级证书', coin: 50000, diamond: 600 },
        { id: '0i', name: '挪威语Bergenstesten', description: '获得挪威语Bergenstesten等级证书', coin: 55000, diamond: 650 },
        { id: '0j', name: '丹麦语Studieprøven', description: '获得丹麦语Studieprøven等级证书', coin: 52000, diamond: 620 },
        { id: '0k', name: '芬兰语YKI', description: '获得芬兰语YKI等级证书', coin: 58000, diamond: 680 },
        { id: '0l', name: '冰岛语Íslenskupróf', description: '获得冰岛语Íslenskupróf等级证书', coin: 45000, diamond: 550 },
        { id: '0m', name: '波兰语B2', description: '获得波兰语B2等级证书', coin: 65000, diamond: 750 },
        { id: '0n', name: '捷克语B2', description: '获得捷克语B2等级证书', coin: 62000, diamond: 720 },
        { id: '0o', name: '斯洛伐克语B2', description: '获得斯洛伐克语B2等级证书', coin: 60000, diamond: 700 },
        { id: '0p', name: '匈牙利语B2', description: '获得匈牙利语B2等级证书', coin: 68000, diamond: 780 },
        { id: '0q', name: '罗马尼亚语B2', description: '获得罗马尼亚语B2等级证书', coin: 55000, diamond: 650 },
        { id: '0r', name: '保加利亚语B2', description: '获得保加利亚语B2等级证书', coin: 58000, diamond: 680 },
        { id: '0s', name: '塞尔维亚语B2', description: '获得塞尔维亚语B2等级证书', coin: 62000, diamond: 720 },
        { id: '0t', name: '克罗地亚语B2', description: '获得克罗地亚语B2等级证书', coin: 60000, diamond: 700 },
        { id: '0u', name: '斯洛文尼亚语B2', description: '获得斯洛文尼亚语B2等级证书', coin: 52000, diamond: 620 },
        { id: '0v', name: '爱沙尼亚语B2', description: '获得爱沙尼亚语B2等级证书', coin: 48000, diamond: 580 },
        { id: '0w', name: '拉脱维亚语B2', description: '获得拉脱维亚语B2等级证书', coin: 50000, diamond: 600 },
        { id: '0x', name: '立陶宛语B2', description: '获得立陶宛语B2等级证书', coin: 52000, diamond: 620 },
        { id: '0y', name: '乌克兰语B2', description: '获得乌克兰语B2等级证书', coin: 70000, diamond: 800 },
        { id: '0z', name: '白俄罗斯语B2', description: '获得白俄罗斯语B2等级证书', coin: 45000, diamond: 550 },
        { id: '0A', name: '摩尔多瓦语B2', description: '获得摩尔多瓦语B2等级证书', coin: 40000, diamond: 500 },
        { id: '0B', name: '格鲁吉亚语B2', description: '获得格鲁吉亚语B2等级证书', coin: 75000, diamond: 850 },
        { id: '0C', name: '亚美尼亚语B2', description: '获得亚美尼亚语B2等级证书', coin: 65000, diamond: 750 },
        { id: '0D', name: '阿塞拜疆语B2', description: '获得阿塞拜疆语B2等级证书', coin: 60000, diamond: 700 },
        { id: '0E', name: '哈萨克语B2', description: '获得哈萨克语B2等级证书', coin: 55000, diamond: 650 },
        { id: '0F', name: '乌兹别克语B2', description: '获得乌兹别克语B2等级证书', coin: 50000, diamond: 600 },
        { id: '0G', name: '吉尔吉斯语B2', description: '获得吉尔吉斯语B2等级证书', coin: 45000, diamond: 550 },
        { id: '0H', name: '塔吉克语B2', description: '获得塔吉克语B2等级证书', coin: 42000, diamond: 520 },
        { id: '0I', name: '土库曼语B2', description: '获得土库曼语B2等级证书', coin: 40000, diamond: 500 },
        { id: '0J', name: '蒙古语B2', description: '获得蒙古语B2等级证书', coin: 60000, diamond: 700 },
        { id: '0K', name: '藏语B2', description: '获得藏语B2等级证书', coin: 80000, diamond: 900 },
        { id: '0L', name: '维吾尔语B2', description: '获得维吾尔语B2等级证书', coin: 70000, diamond: 800 },
        { id: '0M', name: '哈萨克语B2', description: '获得哈萨克语B2等级证书', coin: 55000, diamond: 650 },
        { id: '0N', name: '柯尔克孜语B2', description: '获得柯尔克孜语B2等级证书', coin: 48000, diamond: 580 },
        { id: '0O', name: '锡伯语B2', description: '获得锡伯语B2等级证书', coin: 35000, diamond: 450 },
        { id: '0P', name: '达斡尔语B2', description: '获得达斡尔语B2等级证书', coin: 32000, diamond: 420 },
        { id: '0Q', name: '鄂伦春语B2', description: '获得鄂伦春语B2等级证书', coin: 30000, diamond: 400 },
        { id: '0R', name: '鄂温克语B2', description: '获得鄂温克语B2等级证书', coin: 28000, diamond: 380 },
        { id: '0S', name: '赫哲语B2', description: '获得赫哲语B2等级证书', coin: 25000, diamond: 350 },
        { id: '0T', name: '满语B2', description: '获得满语B2等级证书', coin: 40000, diamond: 500 },
        { id: '0U', name: '朝鲜语B2', description: '获得朝鲜语B2等级证书', coin: 65000, diamond: 750 },
        { id: '0V', name: '壮语B2', description: '获得壮语B2等级证书', coin: 35000, diamond: 450 },
        { id: '0W', name: '布依语B2', description: '获得布依语B2等级证书', coin: 32000, diamond: 420 },
        { id: '0X', name: '侗语B2', description: '获得侗语B2等级证书', coin: 30000, diamond: 400 },
        { id: '0Y', name: '瑶语B2', description: '获得瑶语B2等级证书', coin: 28000, diamond: 380 },
        { id: '0Z', name: '白语B2', description: '获得白语B2等级证书', coin: 25000, diamond: 350 },
        { id: '10', name: '土家语B2', description: '获得土家语B2等级证书', coin: 22000, diamond: 320 },
        { id: '11', name: '哈尼语B2', description: '获得哈尼语B2等级证书', coin: 20000, diamond: 300 },
        { id: '12', name: '傣语B2', description: '获得傣语B2等级证书', coin: 18000, diamond: 280 },
        { id: '13', name: '黎语B2', description: '获得黎语B2等级证书', coin: 16000, diamond: 260 },
        { id: '14', name: '傈僳语B2', description: '获得傈僳语B2等级证书', coin: 14000, diamond: 240 },
        { id: '15', name: '佤语B2', description: '获得佤语B2等级证书', coin: 12000, diamond: 220 },
        { id: '16', name: '畲语B2', description: '获得畲语B2等级证书', coin: 10000, diamond: 200 },
        { id: '17', name: '高山语B2', description: '获得高山语B2等级证书', coin: 8000, diamond: 180 },
        { id: '18', name: '拉祜语B2', description: '获得拉祜语B2等级证书', coin: 6000, diamond: 160 },
        { id: '19', name: '水语B2', description: '获得水语B2等级证书', coin: 4000, diamond: 140 },
        { id: '1a', name: '东乡语B2', description: '获得东乡语B2等级证书', coin: 2000, diamond: 120 },
        { id: '1b', name: '纳西语B2', description: '获得纳西语B2等级证书', coin: 1500, diamond: 100 },
        { id: '1c', name: '景颇语B2', description: '获得景颇语B2等级证书', coin: 1000, diamond: 80 },
        { id: '1d', name: '柯尔克孜语B2', description: '获得柯尔克孜语B2等级证书', coin: 800, diamond: 60 },
        { id: '1e', name: '土语B2', description: '获得土语B2等级证书', coin: 600, diamond: 40 },
        { id: '1f', name: '达斡尔语B2', description: '获得达斡尔语B2等级证书', coin: 400, diamond: 20 },
        { id: '1g', name: '仫佬语B2', description: '获得仫佬语B2等级证书', coin: 200, diamond: 10 },
        { id: '1h', name: '羌语B2', description: '获得羌语B2等级证书', coin: 100, diamond: 5 },
        { id: '1i', name: '布朗语B2', description: '获得布朗语B2等级证书', coin: 50, diamond: 2 },
        { id: '1j', name: '撒拉语B2', description: '获得撒拉语B2等级证书', coin: 25, diamond: 1 },
        { id: '1k', name: '毛南语B2', description: '获得毛南语B2等级证书', coin: 20, diamond: 1 },
        { id: '1l', name: '仡佬语B2', description: '获得仡佬语B2等级证书', coin: 15, diamond: 1 },
        { id: '1m', name: '锡伯语B2', description: '获得锡伯语B2等级证书', coin: 10, diamond: 1 },
        { id: '1n', name: '阿昌语B2', description: '获得阿昌语B2等级证书', coin: 8, diamond: 1 },
        { id: '1o', name: '普米语B2', description: '获得普米语B2等级证书', coin: 6, diamond: 1 },
        { id: '1p', name: '塔吉克语B2', description: '获得塔吉克语B2等级证书', coin: 4, diamond: 1 },
        { id: '1q', name: '怒语B2', description: '获得怒语B2等级证书', coin: 2, diamond: 1 },
        { id: '1r', name: '乌孜别克语B2', description: '获得乌孜别克语B2等级证书', coin: 1, diamond: 1 },
        { id: '1s', name: '俄罗斯语B2', description: '获得俄罗斯语B2等级证书', coin: 80000, diamond: 900 },
        { id: '1t', name: '鄂温克语B2', description: '获得鄂温克语B2等级证书', coin: 28000, diamond: 380 }
    ]
}; 